fs = 48000; % hard code sample rate
win = hamming(0.03*fs,"periodic");
overlapLength = round(0.75*numel(win));
extractor = audioFeatureExtractor('Window',win, ...
        'OverlapLength',overlapLength, ...
        'SampleRate',fs, ...
        'SpectralDescriptorInput','melSpectrum', ...
        ...
        'gtcc',true, ...
        'gtccDelta',true, ...
        'gtccDeltaDelta',true, ...
        'spectralSlope',true, ...
        'spectralFlux',true, ...
        'spectralCentroid',true, ...
        'spectralEntropy',true, ...
        'pitch',true, ...
        'harmonicRatio',true);