fs = 48000; % hard code sample rate
win = hamming(0.03*fs,"periodic");
overlapLength = round(0.75*numel(win));
extractor = audioFeatureExtractor('Window',win, ...
        'OverlapLength',overlapLength, ...
        'SampleRate',fs, ...
        'SpectralDescriptorInput','melSpectrum', ...
        ...
        'mfcc',true, ...
        'mfccDelta',true, ...
        'mfccDeltaDelta',true, ...
        'gtcc',true, ...
        'gtccDelta',true, ...
        'gtccDeltaDelta',true, ...
        'spectralCentroid',true, ...
        'spectralCrest',true, ...
        'spectralDecrease',true, ...
        'spectralEntropy',true, ...
        'spectralFlatness',true, ...
        'spectralFlux',true, ...
        'spectralKurtosis',true, ...
        'spectralRolloffPoint',true, ...
        'spectralSkewness',true, ...
        'spectralSlope',true, ...
        'spectralSpread',true, ...
        'pitch',true, ...
        'harmonicRatio',true);
    